### ISSUE TITLE
[V6] Roadmap

### ISSUE THREAD

**Issue by aitboudad** [ngx-formly/ngx-formly#1365]
- [x] add `lazy` rendering https://github.com/ngx-formly/ngx-formly/issues/1215
- [ ] Add `validationMessages` pipe which will replace `formly-validation-message` component (fix #1297)
- [x] Add  `expressions` which will replace/merge `hideExpression` and `expressionProperties` with a new   signature `(field) => any`
- [x] move `FieldArrayType` into sub module
- [x] expose `options.buildField` which will replace the internal `options._buildForm` (#1583)
- [x] expose `options.checkField` which will replace the internal `options._checkField` (#1773)
- [x] Deprecate using `FormlyGroup` in favor of `FormlyField`
- [x] allow passing observable for expression in asyncValidators
- [x] Move template type to submodule
- [x] [getFieldId](https://github.com/ngx-formly/ngx-formly/blob/master/src/core/src/lib/utils.ts#L6): take account of root path instead of index
- [ ] more UI :)
    - [ ] https://vmware.github.io/clarity/ (#1292)
    - [ ] http://truly-ui.com/ (#1275)
    - [ ] https://akveo.github.io/nebular/
    - [x] https://ng.ant.design/docs/introduce/en
    - [ ] DevExtreme #1448

**Comment by thorgod** [comment]
@aitboudad 
Great job! Just upgraded to version 5 r12, looking forward to seeing the FieldArrayType module.  

I do have some questions about performance with large amounts of fields/data with FieldArrayType to make sure I am not doing something stupid on my end with FieldArrayType. I will be making a issue with an example.

**Comment by KangoV** [comment]
Any idea on timescales for the Nebula template?

**Comment by aitboudad** [comment]
@KangoV from my side right now I'm busy with other stuff so not anytime soon, sorry :pray:!

**Comment by Aashir1** [comment]
Hi @aitboudad, hope you are doing great, can you please let me know about the release date of V6.

**Comment by aitboudad** [comment]
@Aashir1 some features are already ported to `V5` so in overall `V6` is about:

- Refactoring our codebase (**done**)
- remove `V5` deprecation (**done**)
- OnPush CD by default which (**done**)
- Async rendering + 2 features related to Form events (**todo**)

Once the remaining parts are done (not too much) we can release the `V6` but there is no timeline (which depends on my free time) for now!

**Comment by manuelmeister** [comment]
How can I help bring v6 to release?

**Comment by aitboudad** [comment]
Note: Next week we'll start releasing an alpha version.

@manuelmeister left some tasks:
- Async rendering (much advanced)
- add UPGRADE file similar to https://github.com/ngx-formly/ngx-formly/blob/main/UPGRADE-5.0.md
- 2 features related to Form events (will provide you more details, just contact me by mail)
